name: BTC Private Key Finder

on:
  workflow_dispatch:
    inputs:
      target_address:
        description: 'Target Bitcoin address (compressed)'
        required: true
        default: '1PWo3JeB9jrGwfHDNpdGK54CRas7fsVzXU'
      start_range:
        description: 'Start range (hex)'
        required: true
        default: '0000000000000000000000000000000000000000000000400000000000000000'
      end_range:
        description: 'End range (hex)'
        required: true
        default: '00000000000000000000000000000000000000000000007fffffffffffffffff'
      chunk_size:
        description: 'Keys per chunk'
        required: false
        default: '100000'

jobs:
  run-finder:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Максимальное время выполнения (6 часов)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Обновлено до v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5  # Обновлено до v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev libssl-dev

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install ecdsa base58 tqdm

    - name: Create and run BTC Finder
      run: |
        # [Ваш код Python остается без изменений]
        python btc_finder.py

    - name: Upload results
      uses: actions/upload-artifact@v4  # Обновлено до v4
      if: always()
      with:
        name: btc-finder-results
        path: |
          btc_key_finder.log
          found_key.txt
