name: BTC Private Key Finder

on:
  workflow_dispatch:
    inputs:
      target_address:
        description: 'Target Bitcoin address (compressed)'
        required: true
        default: '1PWo3JeB9jrGwfHDNpdGK54CRas7fsVzXU'
      start_range:
        description: 'Start range (hex)'
        required: true
        default: '0000000000000000000000000000000000000000000000400000000000000000'
      end_range:
        description: 'End range (hex)'
        required: true
        default: '00000000000000000000000000000000000000000000007fffffffffffffffff'
      chunk_size:
        description: 'Keys per sequential chunk'
        required: false
        default: '10000000'

jobs:
  run-finder:
    runs-on: ubuntu-latest
    timeout-minutes: 1440  # 24 hours max runtime

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev libssl-dev
        pip install ecdsa base58 tqdm

    - name: Create Python script
      run: |
        cat > btc_finder.py << 'EOF'
        [PASTE THE ENTIRE PYTHON CODE ABOVE HERE]
        EOF

    - name: Run BTC Finder
      run: python btc_finder.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: btc-finder-results
        path: |
          btc_key_finder.log
          found_key.txt
          checked_ranges.json
