name: BTC Key Finder (Hybrid Random+Sequential)

on:
  workflow_dispatch:
    inputs:
      target_address:
        description: 'Bitcoin address to find (compressed)'
        required: true
        default: '1PWo3JeB9jrGwfHDNpdGK54CRas7fsVzXU'

jobs:
  find_keys:
    runs-on: ubuntu-latest
    timeout-minutes: 4320  # 3 days max runtime

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev libssl-dev
        pip install ecdsa base58 tqdm

    - name: Run hybrid finder
      run: |
        python main.py "${{ github.event.inputs.target_address }}"

    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: btc-finder-results
        path: |
          btc_finder.log
          found_keys.txt
          checked_ranges.json
